apiVersion: v1
kind: Namespace
metadata:
  name: prj-tomcat
---
apiVersion: apps/v1

kind: Deployment
metadata:
  namespace: prj-tomcat
  name: tomcatwas
  labels:
    app: tomcatwas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcatwas
  template:
    metadata:
      labels:
        app: tomcatwas
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: tomcatwas
      containers:
      - name: tomcat
        image: 627994959940.dkr.ecr.ap-northeast-2.amazonaws.com/kr-ecr
        resources:
          requests:
            cpu: "500m"
          limits:
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
  namespace: prj-tomcat
spec:
  selector:
    app: tomcatwas
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tomcat-hpa
  namespace: prj-tomcat
spec:
  scaleTargetRef:
    apiVersion: apps/v1

    kind: Deployment
    name: tomcatwas
  minReplicas: 2
  maxReplicas: 150
  targetCPUUtilizationPercentage: 50

